test_mod: false
business:
    bst_id: 10001 #号码百事通
    jh_id: 10002 #交通银行万里行
    pajf_id: 10003 #平安银行积分商城
    padkh_id: 10004 #平安银行大客户
unit:
    zb_id: 10000 #闸北区局
tcsd:
    length: 10 #单次查询最大个数
csb_interface:
    # for test
    send_point_order_url: 'http://222.68.185.224:10088/SendPointOrder/V1_0'
    point_order_status_url: 'http://222.68.185.224:10088/PointOrderStatus/V1_0'
    update_point_order_status_url: 'http://222.68.185.224:10088/UpdatePointOrderStatus/V1_0'
    point_update_trans_status_url: 'http://222.68.185.224:10088/PointUpdateTransStatus/V1_0'
    # for production
    #send_point_order_url: 'http://172.16.203.100:3000/SendPointOrder/V1_0'
    #point_order_status_url: 'http://172.16.203.100:3000/PointOrderStatus/V1_0'
    #update_point_order_status_url: 'http://172.16.203.100:3000/UpdatePointOrderStatus/V1_0'
    #point_update_trans_status_url: 'http://172.16.203.100:3000/PointUpdateTransStatus/V1_0'
    post_name: '闸北邮政' #XX配送商
    bst_name: '积分平台' #积分平台
    max_time_valve: 10 #每次发送的最大条数
    order_type_1: 1 #原始订单
    order_type_2: 2 #合并订单
    active_code: '0991' #口令验证码
    query_time: '00:00:00' #查询订单截止时间(弃用)
    query_period: 1 #查询订单周期(天)