require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CountryCodesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # CountryCode. As you add validations to CountryCode, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CountryCodesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all country_codes as @country_codes" do
      country_code = CountryCode.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:country_codes)).to eq([country_code])
    end
  end

  describe "GET show" do
    it "assigns the requested country_code as @country_code" do
      country_code = CountryCode.create! valid_attributes
      get :show, {:id => country_code.to_param}, valid_session
      expect(assigns(:country_code)).to eq(country_code)
    end
  end

  describe "GET new" do
    it "assigns a new country_code as @country_code" do
      get :new, {}, valid_session
      expect(assigns(:country_code)).to be_a_new(CountryCode)
    end
  end

  describe "GET edit" do
    it "assigns the requested country_code as @country_code" do
      country_code = CountryCode.create! valid_attributes
      get :edit, {:id => country_code.to_param}, valid_session
      expect(assigns(:country_code)).to eq(country_code)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CountryCode" do
        expect {
          post :create, {:country_code => valid_attributes}, valid_session
        }.to change(CountryCode, :count).by(1)
      end

      it "assigns a newly created country_code as @country_code" do
        post :create, {:country_code => valid_attributes}, valid_session
        expect(assigns(:country_code)).to be_a(CountryCode)
        expect(assigns(:country_code)).to be_persisted
      end

      it "redirects to the created country_code" do
        post :create, {:country_code => valid_attributes}, valid_session
        expect(response).to redirect_to(CountryCode.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved country_code as @country_code" do
        post :create, {:country_code => invalid_attributes}, valid_session
        expect(assigns(:country_code)).to be_a_new(CountryCode)
      end

      it "re-renders the 'new' template" do
        post :create, {:country_code => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested country_code" do
        country_code = CountryCode.create! valid_attributes
        put :update, {:id => country_code.to_param, :country_code => new_attributes}, valid_session
        country_code.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested country_code as @country_code" do
        country_code = CountryCode.create! valid_attributes
        put :update, {:id => country_code.to_param, :country_code => valid_attributes}, valid_session
        expect(assigns(:country_code)).to eq(country_code)
      end

      it "redirects to the country_code" do
        country_code = CountryCode.create! valid_attributes
        put :update, {:id => country_code.to_param, :country_code => valid_attributes}, valid_session
        expect(response).to redirect_to(country_code)
      end
    end

    describe "with invalid params" do
      it "assigns the country_code as @country_code" do
        country_code = CountryCode.create! valid_attributes
        put :update, {:id => country_code.to_param, :country_code => invalid_attributes}, valid_session
        expect(assigns(:country_code)).to eq(country_code)
      end

      it "re-renders the 'edit' template" do
        country_code = CountryCode.create! valid_attributes
        put :update, {:id => country_code.to_param, :country_code => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested country_code" do
      country_code = CountryCode.create! valid_attributes
      expect {
        delete :destroy, {:id => country_code.to_param}, valid_session
      }.to change(CountryCode, :count).by(-1)
    end

    it "redirects to the country_codes list" do
      country_code = CountryCode.create! valid_attributes
      delete :destroy, {:id => country_code.to_param}, valid_session
      expect(response).to redirect_to(country_codes_url)
    end
  end

end
