require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GoodstypesController do

  # This should return the minimal set of attributes required to create a valid
  # Goodstype. As you add validations to Goodstype, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "gtno" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GoodstypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all goodstypes as @goodstypes" do
      goodstype = Goodstype.create! valid_attributes
      get :index, {}, valid_session
      assigns(:goodstypes).should eq([goodstype])
    end
  end

  describe "GET show" do
    it "assigns the requested goodstype as @goodstype" do
      goodstype = Goodstype.create! valid_attributes
      get :show, {:id => goodstype.to_param}, valid_session
      assigns(:goodstype).should eq(goodstype)
    end
  end

  describe "GET new" do
    it "assigns a new goodstype as @goodstype" do
      get :new, {}, valid_session
      assigns(:goodstype).should be_a_new(Goodstype)
    end
  end

  describe "GET edit" do
    it "assigns the requested goodstype as @goodstype" do
      goodstype = Goodstype.create! valid_attributes
      get :edit, {:id => goodstype.to_param}, valid_session
      assigns(:goodstype).should eq(goodstype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Goodstype" do
        expect {
          post :create, {:goodstype => valid_attributes}, valid_session
        }.to change(Goodstype, :count).by(1)
      end

      it "assigns a newly created goodstype as @goodstype" do
        post :create, {:goodstype => valid_attributes}, valid_session
        assigns(:goodstype).should be_a(Goodstype)
        assigns(:goodstype).should be_persisted
      end

      it "redirects to the created goodstype" do
        post :create, {:goodstype => valid_attributes}, valid_session
        response.should redirect_to(Goodstype.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved goodstype as @goodstype" do
        # Trigger the behavior that occurs when invalid params are submitted
        Goodstype.any_instance.stub(:save).and_return(false)
        post :create, {:goodstype => { "gtno" => "invalid value" }}, valid_session
        assigns(:goodstype).should be_a_new(Goodstype)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Goodstype.any_instance.stub(:save).and_return(false)
        post :create, {:goodstype => { "gtno" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested goodstype" do
        goodstype = Goodstype.create! valid_attributes
        # Assuming there are no other goodstypes in the database, this
        # specifies that the Goodstype created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Goodstype.any_instance.should_receive(:update).with({ "gtno" => "MyString" })
        put :update, {:id => goodstype.to_param, :goodstype => { "gtno" => "MyString" }}, valid_session
      end

      it "assigns the requested goodstype as @goodstype" do
        goodstype = Goodstype.create! valid_attributes
        put :update, {:id => goodstype.to_param, :goodstype => valid_attributes}, valid_session
        assigns(:goodstype).should eq(goodstype)
      end

      it "redirects to the goodstype" do
        goodstype = Goodstype.create! valid_attributes
        put :update, {:id => goodstype.to_param, :goodstype => valid_attributes}, valid_session
        response.should redirect_to(goodstype)
      end
    end

    describe "with invalid params" do
      it "assigns the goodstype as @goodstype" do
        goodstype = Goodstype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Goodstype.any_instance.stub(:save).and_return(false)
        put :update, {:id => goodstype.to_param, :goodstype => { "gtno" => "invalid value" }}, valid_session
        assigns(:goodstype).should eq(goodstype)
      end

      it "re-renders the 'edit' template" do
        goodstype = Goodstype.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Goodstype.any_instance.stub(:save).and_return(false)
        put :update, {:id => goodstype.to_param, :goodstype => { "gtno" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested goodstype" do
      goodstype = Goodstype.create! valid_attributes
      expect {
        delete :destroy, {:id => goodstype.to_param}, valid_session
      }.to change(Goodstype, :count).by(-1)
    end

    it "redirects to the goodstypes list" do
      goodstype = Goodstype.create! valid_attributes
      delete :destroy, {:id => goodstype.to_param}, valid_session
      response.should redirect_to(goodstypes_url)
    end
  end

end
