require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ManualStocksController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ManualStock. As you add validations to ManualStock, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "no" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ManualStocksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all manual_stocks as @manual_stocks" do
      manual_stock = ManualStock.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:manual_stocks)).to eq([manual_stock])
    end
  end

  describe "GET show" do
    it "assigns the requested manual_stock as @manual_stock" do
      manual_stock = ManualStock.create! valid_attributes
      get :show, {:id => manual_stock.to_param}, valid_session
      expect(assigns(:manual_stock)).to eq(manual_stock)
    end
  end

  describe "GET new" do
    it "assigns a new manual_stock as @manual_stock" do
      get :new, {}, valid_session
      expect(assigns(:manual_stock)).to be_a_new(ManualStock)
    end
  end

  describe "GET edit" do
    it "assigns the requested manual_stock as @manual_stock" do
      manual_stock = ManualStock.create! valid_attributes
      get :edit, {:id => manual_stock.to_param}, valid_session
      expect(assigns(:manual_stock)).to eq(manual_stock)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ManualStock" do
        expect {
          post :create, {:manual_stock => valid_attributes}, valid_session
        }.to change(ManualStock, :count).by(1)
      end

      it "assigns a newly created manual_stock as @manual_stock" do
        post :create, {:manual_stock => valid_attributes}, valid_session
        expect(assigns(:manual_stock)).to be_a(ManualStock)
        expect(assigns(:manual_stock)).to be_persisted
      end

      it "redirects to the created manual_stock" do
        post :create, {:manual_stock => valid_attributes}, valid_session
        expect(response).to redirect_to(ManualStock.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved manual_stock as @manual_stock" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(ManualStock).to receive(:save).and_return(false)
        post :create, {:manual_stock => { "no" => "invalid value" }}, valid_session
        expect(assigns(:manual_stock)).to be_a_new(ManualStock)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(ManualStock).to receive(:save).and_return(false)
        post :create, {:manual_stock => { "no" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested manual_stock" do
        manual_stock = ManualStock.create! valid_attributes
        # Assuming there are no other manual_stocks in the database, this
        # specifies that the ManualStock created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(ManualStock).to receive(:update).with({ "no" => "MyString" })
        put :update, {:id => manual_stock.to_param, :manual_stock => { "no" => "MyString" }}, valid_session
      end

      it "assigns the requested manual_stock as @manual_stock" do
        manual_stock = ManualStock.create! valid_attributes
        put :update, {:id => manual_stock.to_param, :manual_stock => valid_attributes}, valid_session
        expect(assigns(:manual_stock)).to eq(manual_stock)
      end

      it "redirects to the manual_stock" do
        manual_stock = ManualStock.create! valid_attributes
        put :update, {:id => manual_stock.to_param, :manual_stock => valid_attributes}, valid_session
        expect(response).to redirect_to(manual_stock)
      end
    end

    describe "with invalid params" do
      it "assigns the manual_stock as @manual_stock" do
        manual_stock = ManualStock.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(ManualStock).to receive(:update).and_return(false)
        put :update, {:id => manual_stock.to_param, :manual_stock => { "no" => "invalid value" }}, valid_session
        expect(assigns(:manual_stock)).to eq(manual_stock)
      end

      it "re-renders the 'edit' template" do
        manual_stock = ManualStock.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(ManualStock).to receive(:update).and_return(false)
        put :update, {:id => manual_stock.to_param, :manual_stock => { "no" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested manual_stock" do
      manual_stock = ManualStock.create! valid_attributes
      expect {
        delete :destroy, {:id => manual_stock.to_param}, valid_session
      }.to change(ManualStock, :count).by(-1)
    end

    it "redirects to the manual_stocks list" do
      manual_stock = ManualStock.create! valid_attributes
      delete :destroy, {:id => manual_stock.to_param}, valid_session
      expect(response).to redirect_to(manual_stocks_url)
    end
  end

end
