require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrdersController do

  # This should return the minimal set of attributes required to create a valid
  # Business. As you add validations to Business, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BuniessesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  shared_examples("user/admin access to orders") do
    describe "GET index" do
      it "assigns all orders as @orders" do
        get :index
        expect(assigns(:orders)).to eq([@order1, @order2, @order3])
      end

      it "renders the index view" do
        get :index
        expect(response).to render_template :index
      end
    end

    describe "GET show" do
      it "assigns the requested order as @order" do
        get :show, id: @order1
        expect(assigns(:order)).to eq(@order1)
      end

      it "renders the show view" do
        get :show, id: @order1
        expect(response).to render_template :show
      end
    end

    describe "GET new" do
      it "assigns a new order as @order" do
        get :new
        expect(assigns(:order)).to be_a_new(Order)
      end

      it "renders the new view" do
        get :new
        expect(response).to render_template :new
      end
    end

    describe "GET edit" do
      it "assigns the requested order as @order" do
        get :edit, id: @order1
        expect(assigns(:order)).to eq(@order1)
      end

      it "renders the edit view" do
        get :edit, id: @order1
        expect(response).to render_template :edit
      end
    end

    describe "POST create" do
      context "with valid params" do
        it "creates a new Order" do
            expect { post :create, order: FactoryGirl.attributes_for(:order) }.to change(Order, :count).by(1)
        end

        it "assigns a newly created order as @order" do
          post :create, order: FactoryGirl.attributes_for(:order)
          expect(assigns(:order)).to be_a(Order)
          expect(assigns(:order)).to be_persisted
        end

        it "redirects to the created order" do
          post :create, order: FactoryGirl.attributes_for(:order)
          expect(response).to redirect_to(Order.last)
        end
      end

      context "with invalid params" do
        it "assigns a newly created but unsaved order as @order" do
          expect{post :create, order: FactoryGirl.attributes_for(:invalid_order)}.to_not change(Order, :count)
        end

        it "re-renders the 'new' template" do
          post :create, order: FactoryGirl.attributes_for(:invalid_order)
          expect(response).to render_template :new
        end
      end
    end

    describe "PATCH update" do
      context "with valid params" do
        it "locates the requested @order" do
          patch :update, id: @order1, order: FactoryGirl.attributes_for(:update_order)
          expect(assigns(:order)).to eq @order1
        end

        it "changes @order's attributes" do
          patch :update, id: @order1, order: FactoryGirl.attributes_for(:update_order)
          @order1.reload
          expect(@order1.no).to eq("20140401001")
          expect(@order1.good_amount).to eq(200)
          expect(@order1.good_sum).to eq(200.1)
        end

        it "redirects to the order" do
          patch :update, id: @order1, order: FactoryGirl.attributes_for(:update_order)
          expect(response).to redirect_to @order1
        end
      end

      context "with invalid params" do
        it "does not change the order's attributes" do
          put :update, id: @order1, order: FactoryGirl.attributes_for(:invalid_order)
          @order1.reload
          expect(@order1.good_sum).to eq(1.5)
          expect(@order1.good_amount).to_not eq(0)
        end

        it "re-renders the 'edit' template" do
          put :update, id: @order1, order: FactoryGirl.attributes_for(:invalid_order)
          expect(response).to render_template("edit")
        end
      end
    end

    describe "DELETE destroy" do

      it "destroys the requested order" do
        expect {
          delete :destroy, id: @order1
        }.to change(Order, :count).by(-1)
      end

      it "redirects to the orders list" do
        delete :destroy, id: @order1
        expect(response).to redirect_to(orders_url)
      end

    end
  end

  shared_examples("guest access to orders") do
    describe "GET index" do
      it "should login" do
        get :index
        expect(response).to redirect_to "/users/sign_in"
      end
    end

    describe "GET show" do
      it "should login" do
        get :show, id: @order1
        expect(response).to redirect_to "/users/sign_in"
      end
    end

    describe "GET new" do
      it "should login" do
        get :new
        expect(response).to redirect_to "/users/sign_in"
      end
    end

    describe "GET edit" do
      it "should login" do
        get :edit, id: @order1
        expect(response).to redirect_to "/users/sign_in"
      end
    end

    describe "POST create" do
        it "should login" do
          post :create, order: FactoryGirl.attributes_for(:order)
          expect(response).to redirect_to "/users/sign_in"
        end
    end

    describe "PATCH update" do
        it "should login" do
          patch :update, id: @order1, order: FactoryGirl.attributes_for(:order)
          expect(response).to redirect_to "/users/sign_in"
        end
    end

    describe "DELETE destroy" do
      it "should login" do
        delete :destroy, id: @order1
        expect(response).to redirect_to "/users/sign_in"
      end
    end
  end

  describe "admin access" do
    before :each do 
      #FactoryGirl.create(:order)
      FactoryGirl.create(:superadmin)

      @superadmin = User.find 1
      @order1 = FactoryGirl.create(:order)
      @order2 = FactoryGirl.create(:order)
      @order3 = FactoryGirl.create(:order)
      sign_in @superadmin
    end

    it_behaves_like "user/admin access to orders"
    
  end

  describe "guess access" do
    before :each do 
      #FactoryGirl.create(:order)
      @order1 = FactoryGirl.create(:order)
      @order2 = FactoryGirl.create(:order)
      @order3 = FactoryGirl.create(:order)
    end

    it_behaves_like "guest access to orders"
  end
end
