require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrderreturnsController do

  # This should return the minimal set of attributes required to create a valid
  # Orderreturn. As you add validations to Orderreturn, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "order_detail_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrderreturnsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all orderreturns as @orderreturns" do
      orderreturn = Orderreturn.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:orderreturns)).to eq([orderreturn])
    end
  end

  describe "GET show" do
    it "assigns the requested orderreturn as @orderreturn" do
      orderreturn = Orderreturn.create! valid_attributes
      get :show, {:id => orderreturn.to_param}, valid_session
      expect(assigns(:orderreturn)).to eq(orderreturn)
    end
  end

  describe "GET new" do
    it "assigns a new orderreturn as @orderreturn" do
      get :new, {}, valid_session
      expect(assigns(:orderreturn)).to be_a_new(Orderreturn)
    end
  end

  describe "GET edit" do
    it "assigns the requested orderreturn as @orderreturn" do
      orderreturn = Orderreturn.create! valid_attributes
      get :edit, {:id => orderreturn.to_param}, valid_session
      expect(assigns(:orderreturn)).to eq(orderreturn)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Orderreturn" do
        expect {
          post :create, {:orderreturn => valid_attributes}, valid_session
        }.to change(Orderreturn, :count).by(1)
      end

      it "assigns a newly created orderreturn as @orderreturn" do
        post :create, {:orderreturn => valid_attributes}, valid_session
        expect(assigns(:orderreturn)).to be_a(Orderreturn)
        expect(assigns(:orderreturn)).to be_persisted
      end

      it "redirects to the created orderreturn" do
        post :create, {:orderreturn => valid_attributes}, valid_session
        expect(response).to redirect_to(Orderreturn.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved orderreturn as @orderreturn" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Orderreturn).to receive(:save).and_return(false)
        post :create, {:orderreturn => { "order_detail_id" => "invalid value" }}, valid_session
        expect(assigns(:orderreturn)).to be_a_new(Orderreturn)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Orderreturn).to receive(:save).and_return(false)
        post :create, {:orderreturn => { "order_detail_id" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested orderreturn" do
        orderreturn = Orderreturn.create! valid_attributes
        # Assuming there are no other orderreturns in the database, this
        # specifies that the Orderreturn created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Orderreturn).to receive(:update).with({ "order_detail_id" => "1" })
        put :update, {:id => orderreturn.to_param, :orderreturn => { "order_detail_id" => "1" }}, valid_session
      end

      it "assigns the requested orderreturn as @orderreturn" do
        orderreturn = Orderreturn.create! valid_attributes
        put :update, {:id => orderreturn.to_param, :orderreturn => valid_attributes}, valid_session
        expect(assigns(:orderreturn)).to eq(orderreturn)
      end

      it "redirects to the orderreturn" do
        orderreturn = Orderreturn.create! valid_attributes
        put :update, {:id => orderreturn.to_param, :orderreturn => valid_attributes}, valid_session
        expect(response).to redirect_to(orderreturn)
      end
    end

    describe "with invalid params" do
      it "assigns the orderreturn as @orderreturn" do
        orderreturn = Orderreturn.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Orderreturn).to receive(:save).and_return(false)
        put :update, {:id => orderreturn.to_param, :orderreturn => { "order_detail_id" => "invalid value" }}, valid_session
        expect(assigns(:orderreturn)).to eq(orderreturn)
      end

      it "re-renders the 'edit' template" do
        orderreturn = Orderreturn.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Orderreturn).to receive(:save).and_return(false)
        put :update, {:id => orderreturn.to_param, :orderreturn => { "order_detail_id" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested orderreturn" do
      orderreturn = Orderreturn.create! valid_attributes
      expect {
        delete :destroy, {:id => orderreturn.to_param}, valid_session
      }.to change(Orderreturn, :count).by(-1)
    end

    it "redirects to the orderreturns list" do
      orderreturn = Orderreturn.create! valid_attributes
      delete :destroy, {:id => orderreturn.to_param}, valid_session
      expect(response).to redirect_to(orderreturns_url)
    end
  end

end
